# Generated by Django 5.1.7 on 2026-03-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditLog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User login'), ('LOGOUT', 'User logout'), ('USER_CREATE', 'User created'), ('USER_UPDATE', 'User updated'), ('USER_DELETE', 'User deleted'), ('USER_ACTIVATE', 'User activated'), ('USER_DEACTIVATE', 'User deactivated'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_COMPLETE', 'Password reset completed'), ('PROFILE_UPDATE', 'Profile updated'), ('PERMISSION_CHANGE', 'User permissions changed'), ('EMAIL_SEND_FAILURE', 'Email send failure'), ('USER_LIST_ACCESS', 'User list accessed'), ('USER_DETAIL_ACCESS', 'User detail accessed'), ('SECURITY_INCIDENT_CREATE', 'Security incident created'), ('SECURITY_INCIDENT_STATUS_UPDATE', 'Security incident status updated'), ('COMPLIANCE_POLICY_UPDATE', 'Compliance policy updated')], max_length=50),
        ),
    ]
