# Generated by Django 5.1.7 on 2026-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Officer', 'Officer'), ('Stakeholder', 'Stakeholder')], max_length=20),
        ),
    ]
